# permissions for end users to edit bills.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bill-editor-role
rules:
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - bills
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - bills/status
  verbs:
  - get
