# permissions for end users to view bills.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bill-viewer-role
rules:
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - bills
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - bills/status
  verbs:
  - get
