# permissions for end users to view calculations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calculation-viewer-role
rules:
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - calculations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - calculations/status
  verbs:
  - get
