# permissions for end users to edit results.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: result-editor-role
rules:
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - results
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - results/status
  verbs:
  - get
