---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - calculations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - calculations/finalizers
  verbs:
  - update
- apiGroups:
  - calculator.sap.com.calculator.sap.com
  resources:
  - calculations/status
  verbs:
  - get
  - patch
  - update
